/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.usc.dao.User;
import com.usc.service.UsersManager;
import com.usc.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-26-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action
{
	private User u;
	private UsersManager um;

	public void setU(User u)
	{
		this.u = u;
	}

	public void setUm(UsersManager um)
	{
		this.um = um;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		u.setUsername(loginForm.getUsername().trim());
		u.setPassword(um.encoderByMd5(loginForm.getPassword().trim()));
		if(um.checkUser(u))
			return mapping.findForward("success");
		return mapping.findForward("input");
	}
}