/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sun.org.apache.bcel.internal.generic.RET;
import com.usc.dao.User;
import com.usc.service.UsersManager;
import com.usc.struts.form.RegisterForm;

/**
 * MyEclipse Struts Creation date: 06-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/register" name="registerForm" input="/register.jsp"
 *                scope="request" validate="true"
 */
public class RegisterAction extends Action
{
	private User u;
	private UsersManager um;

	public void setU(User u)
	{
		this.u = u;
	}

	public void setUm(UsersManager um)
	{
		this.um = um;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
//		try
//		{
//			PrintWriter out=response.getWriter();//用于向客户端输出信息
//			String userName=request.getParameter("userName");//从$.ajax里面的附带参数表中获取数据.
//			System.out.println("userName："+userName);
//			if(userName.equals("jsjmz"))//假设用户名只能是china
//			{
//				System.out.println("exist");
//			  out.print("用户名存在");//向客户端发送信息，会被传到回调函数的data参数中
//			  out.flush();
//			}
//			
//		} catch (Exception e)
//		{
//			e.printStackTrace();
//		}
		
		
		RegisterForm registerForm = (RegisterForm) form;// TODO Auto-generated

		if (null == registerForm.getUsername()
				|| null == registerForm.getPassword()
				|| null == registerForm.getRepassword()
				|| 0 == registerForm.getUsername().trim().length()
				|| 0 == registerForm.getPassword().trim().length()
				|| 0 == registerForm.getRepassword().trim().length())
		{
			return mapping.findForward("input");
		}

		else if (registerForm.getPassword().trim().equals(
				registerForm.getRepassword().trim())
				&& um.checkUserName(registerForm.getUsername()))
		{
			u.setUsername(registerForm.getUsername().trim());
			u.setPassword(um.encoderByMd5(registerForm.getPassword().trim()));
			um.addUser(u);
			return mapping.findForward("success");
		}
		return mapping.findForward("input");
	}
}