/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.DAO.HBDAO;
import com.pojo.Hb;
import com.yourcompany.struts.form.AddForm;


public class AddAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddForm addForm = (AddForm) form;
		int uid=addForm.getUid();
		String name=addForm.getUname();
		String pass=addForm.getUpass();
		Hb user=new Hb(uid,name,pass);
		HBDAO dao=new HBDAO();
		dao.AddHB(user);
		List<Hb> list=dao.getAll();
		dao.closeSession();
	
			request.getSession().setAttribute("rs",list);
		return mapping.findForward("go");
	
		
	}
}