/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.web;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Blob;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;
import org.hibernate.Hibernate;

import com.DAO.PhotoDAO;
import com.pojo.Photo;

public class IndexAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		IndexForm indexForm = (IndexForm) form;
		String pname=indexForm.getPanme();
		FormFile photo=indexForm.getPhoto();
		System.out.println(pname+"  "+photo.getFileSize()+" "+photo.getContentType());
		Photo p=new Photo();
		p.setPname(pname);
		try {
			byte[] buf=photo.getFileData();
			Blob ph=Hibernate.createBlob(buf);
			p.setPhoto(ph);
			PhotoDAO dao=new PhotoDAO();
			dao.addPhoto(p);
			//∂¡»°
			Photo temp = dao.getByName(pname);
			InputStream in = temp.getPhoto().getBinaryStream();
			OutputStream out=new FileOutputStream(new File("c:\\"+pname+".jpg"));
			in.read(buf);
			out.write(buf);
			in.close();
			out.close();
			request.getSession().setAttribute("link", "c:\\"+pname+".jpg");
			dao.closeSession();
		} catch (FileNotFoundException e) {
			
			e.printStackTrace();
		} catch (IOException e) {
						e.printStackTrace();
		} catch (SQLException e) {
					e.printStackTrace();
		}
	return mapping.findForward("success");
	}
}