/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-15-2009
 * 
 * XDoclet definition:
 * @struts.form name="addStudentForm"
 */
public class AddStudentForm extends ActionForm
{
	/*
	 * Generated fields
	 */

	/** sex property */
	private String sex;

	/** sno property */
	private String sno;

	/** sname property */
	private String sname;

	/** age property */
	private String age;

	/** gname property */
	private String gname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request)
	{
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request)
	{
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex()
	{
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex)
	{
		this.sex = sex;
	}

	/** 
	 * Returns the sno.
	 * @return String
	 */
	public String getSno()
	{
		return sno;
	}

	/** 
	 * Set the sno.
	 * @param sno The sno to set
	 */
	public void setSno(String sno)
	{
		this.sno = sno;
	}

	/** 
	 * Returns the sname.
	 * @return String
	 */
	public String getSname()
	{
		return sname;
	}

	/** 
	 * Set the sname.
	 * @param sname The sname to set
	 */
	public void setSname(String sname)
	{
		this.sname = sname;
	}

	/** 
	 * Returns the age.
	 * @return String
	 */
	public String getAge()
	{
		return age;
	}

	/** 
	 * Set the age.
	 * @param age The age to set
	 */
	public void setAge(String age)
	{
		this.age = age;
	}

	/** 
	 * Returns the gname.
	 * @return String
	 */
	public String getGname()
	{
		return gname;
	}

	/** 
	 * Set the gname.
	 * @param gname The gname to set
	 */
	public void setGname(String gname)
	{
		this.gname = gname;
	}
}