/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;


import com.usc.service.studentService;

/** 
 * MyEclipse Struts
 * Creation date: 06-15-2009
 * 
 * XDoclet definition:
 * @struts.form name="addStudentForm"
 */
public class AddStudentForm extends ActionForm
{
	/*
	 * Generated fields
	 */

	/** sex property */
	private String sex;

	/** sno property */
	private String sno;

	/** sname property */
	private String sname;

	/** age property */
	private Integer age;

	/** gname property */
	private String gname;

	
	
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request)
	{
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex()
	{
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex)
	{
		this.sex = sex;
	}

	/** 
	 * Returns the sno.
	 * @return String
	 */
	public String getSno()
	{
		return sno;
	}

	/** 
	 * Set the sno.
	 * @param sno The sno to set
	 */
	public void setSno(String sno)
	{
		this.sno = sno;
	}

	/** 
	 * Returns the sname.
	 * @return String
	 */
	public String getSname()
	{
		return sname;
	}

	/** 
	 * Set the sname.
	 * @param sname The sname to set
	 */
	public void setSname(String sname)
	{
		this.sname = sname;
	}

	/** 
	 * Returns the age.
	 * @return String
	 */
	public Integer getAge()
	{
		return age;
	}

	/** 
	 * Set the age.
	 * @param age The age to set
	 */
	public void setAge(Integer age)
	{
		this.age = age;
	}

	/** 
	 * Returns the gname.
	 * @return String
	 */
	public String getGname()
	{
		return gname;
	}

	/** 
	 * Set the gname.
	 * @param gname The gname to set
	 */
	public void setGname(String gname)
	{
		this.gname = gname;
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request)
	{
		ActionErrors errors = new ActionErrors();

		if (null == sno || "".equals(sno.trim()))
		{

			errors.add("sno", new ActionMessage("add.error.sno.required"));

		}
		else if( 11 != sno.length() || !sno.matches("[0-9]+"))
		{
			errors.add("sno", new ActionMessage("add.error.sno"));
		}
		if (null == sname || "".equals(sname.trim()))
		{

			errors.add("sname", new ActionMessage("add.error.sname.required"));

		}
		if (null == sex || "".equals(sex.trim()))
		{

			errors.add("sex", new ActionMessage("add.error.sex.required"));

		}
		if (null == age || "".equals(age))
		{

			errors.add("age", new ActionMessage("add.error.age.required"));
		}
		else if(age<1 || age>150 || ! age.toString().matches("[0-9]+"))
		{
			errors.add("age", new ActionMessage("add.error.age"));
		}
		if (null == gname || "".equals(gname.trim()))
		{

			errors.add("gname", new ActionMessage("add.error.gname.required"));

		}
		return errors;
	}
	
}