/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-18-2009
 * 
 * XDoclet definition:
 * @struts.form name="serachbynameForm"
 */
public class SerachbynameForm extends ActionForm
{
	/*
	 * Generated fields
	 */

	/** ÐÕÃû property */
	private String sname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request)
	{
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request)
	{
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sname.
	 * @return String
	 */
	public String getsname()
	{
		return sname;
	}

	/** 
	 * Set the sname.
	 * @param sname The sname to set
	 */
	public void setsname(String sname)
	{
		this.sname = sname;
	}
}