package com.DAOtest;

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by MyEclipse Persistence Tools
 */

public class Student implements java.io.Serializable {

	// Fields

	private Integer studentid;

	private String studentName;



	// Constructors

	/** default constructor */
	public Student() {
	}

	/** minimal constructor */
	public Student(Integer studentid, String studentName) {
		this.studentid = studentid;
		this.studentName = studentName;
	}



	// Property accessors

	public Integer getStudentid() {
		return this.studentid;
	}

	public void setStudentid(Integer studentid) {
		this.studentid = studentid;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}



}