/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.usc.manager.userManager;
import com.usc.struts.form.RegForm;
import com.usc.util.Users;

/**
 * MyEclipse Struts Creation date: 06-06-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/reg" name="regForm" input="/reg.jsp" scope="request"
 *                validate="true"
 */
public class RegAction extends Action
{

	private userManager um;

	public void setUm(userManager um)
	{
		this.um = um;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		RegForm regForm = (RegForm) form;// TODO Auto-generated method stub
		if ("" != regForm.getUname().trim()
				&& regForm.getUpass().trim().equals(
						regForm.getUconfirmpass().trim()))
		{

			// System.out.println(""+regForm.getUconfirmpass());
			Users user = new Users();
			user.setUname(regForm.getUname());
			user.setUpass(regForm.getUpass());
			if (!um.checkUser(user))
			{
				um.addUser(user);
				request.getSession().setAttribute("uname", user.getUname());
				request.getSession().setAttribute("upass", user.getUpass());
				return mapping.findForward("success");
			} else

				return new ActionForward("/error.jsp");
		} else
		{
			return new ActionForward("/index.jsp");
		}

	}
}