package com.hello;
//Generated by MyEclipse

public class HelloImpl implements IHello {
	
	public String example(String message) {
		//自行编写相关的业务方法(数据库的验证)
		return "你输入的信息是"+message+"  欢迎你再来...";
	}
	
}