/*
 * GoogleCodeDownloadURL.java
 *
 * Created on __DATE__, __TIME__
 */

package org.usc.google.code.download;

import java.awt.FileDialog;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

/**
 *
 * @author  __USER__
 */
public class GoogleCodeDownloadURL extends javax.swing.JFrame
{

	/** Creates new form GoogleCodeDownloadURL */
	public GoogleCodeDownloadURL()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jEditorPane1 = new javax.swing.JEditorPane();
		jButton4 = new javax.swing.JButton();
		fileDialog = new FileDialog(this,"´ò¿ªÎÄ¼þ¶Ô»°¿ò",FileDialog.LOAD);
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Google Code\u5730\u5740\u83b7\u53d6\u5668");
		setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));

		jButton1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton1.setText("\u4e0a\u4f20\u6587\u4ef6\u5e76\u83b7\u53d6\u4e0b\u8f7d\u4fe1\u606f");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter()
		{
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				jButton1MouseClicked(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 24));
		jLabel1.setText("Google Code\u4e0b\u8f7d\u5730\u5740\u83b7\u53d6\u5668");

		jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel2.setText("\u987a\u5229\u5236\u4f5cV0.1");

		jLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel3.setText("\u6587  \u4ef6  \u540d\uff1a");

		jLabel4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel4.setText("\u4e0b\u8f7d\u5730\u5740\uff1a");

		jLabel5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel5.setText("\u4e0b\u8f7d\u4fe1\u606f\uff1a");

		jTextField1.setEditable(false);
		jTextField1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jButton2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton2.setText("\u590d\u5236\u5230\u526a\u8d34\u677f");

		jTextField2.setEditable(false);
		jTextField2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jButton3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton3.setText("\u590d\u5236\u5230\u526a\u8d34\u677f");

		jEditorPane1.setEditable(false);
		jEditorPane1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jScrollPane1.setViewportView(jEditorPane1);

		jButton4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton4.setText("\u590d\u5236\u5230\u526a\u8d34\u677f");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
								layout.createSequentialGroup().addContainerGap().addComponent(jLabel2)).addGroup(
								layout.createSequentialGroup().addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												layout.createSequentialGroup().addGap(20, 20, 20).addGroup(
														layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
																layout.createSequentialGroup().addComponent(jLabel4).addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jTextField2,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)).addGroup(
																layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))).addGroup(
												layout.createSequentialGroup().addGap(114, 114, 114).addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18,
														Short.MAX_VALUE).addGroup(
														layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton3)
																.addComponent(jButton2))).addGroup(
												layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jButton4))))).addGap(35, 35, 35)).addGroup(
				layout.createSequentialGroup().addGap(189, 189, 189).addComponent(jButton1).addContainerGap(235, Short.MAX_VALUE)).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(jLabel5).addContainerGap(553, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel2)).addGroup(layout.createSequentialGroup().addGap(35, 35, 35).addComponent(jButton1)))
								.addGap(35, 35, 35).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												layout.createSequentialGroup().addComponent(jLabel3).addGap(30, 30, 30).addGroup(
														layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
																.addComponent(jButton3).addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
																		javax.swing.GroupLayout.PREFERRED_SIZE))).addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jButton2))).addGap(49, 49, 49).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel5).addComponent(jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jButton4))
								.addGap(88, 88, 88)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt)
	{
		fileDialog.setVisible(true);
		String fileName = fileDialog.getFile();
		jTextField1.setText(fileName);
		jTextField2.setText(googleCodeDownLoadURL(fileName));

	}

	/**
	 * ×Ö·û´®URL±àÂë
	 * 
	 * @param filename
	 *            ÎÄ¼þÃû
	 * @return URL±àÂëºóµÄÎÄ¼þÃû
	 */
	private static String stringToURL(String filename)
	{
		String retVal = null;
		try
		{
			retVal = URLEncoder.encode(filename, "UTF-8");// URL±àÂë£¬GBK µ½ UTF-8¸ñÊ½
		}
		catch (UnsupportedEncodingException e)
		{
			e.printStackTrace();
		}
		return retVal;
	}

	/**
	 * »ñÈ¡Google Code ÏÂÔØµØÖ·
	 * 
	 * @param filename
	 *            ÎÄ¼þÃû
	 * @return Google Code ÏÂÔØµØÖ·
	 */
	private static String googleCodeDownLoadURL(String filename)
	{
		final String prefixURL = "http://usc.googlecode.com/files/";// Ç°×º
		String retVal = prefixURL + stringToURL(filename);// Google Code ÏÂÔØµØÖ·
		return retVal;
	}

	/**
	 * ¸´ÖÆµ½¼ôÌù°å
	 * 
	 * @param String
	 *            ÐèÒª¸´ÖÆµÄÎÄ±¾
	 */
	public static void copy(String str)
	{
		StringSelection stsel = new StringSelection(str);
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stsel, stsel);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new GoogleCodeDownloadURL().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JEditorPane jEditorPane1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private FileDialog fileDialog;
	// End of variables declaration//GEN-END:variables

}