/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.DAO.HBDAO;
import com.pojo.Hb;
import com.yourcompany.struts.form.AddForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-15-2009
 * 
 * XDoclet definition:
 * @struts.action path="/add" name="addForm" input="/add.jsp" scope="request" validate="true"
 */
public class AddAction extends Action
{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
//		AddForm addForm = (AddForm) form;// TODO Auto-generated method stub
//		int uid=addForm.getUid();
//		String uname=addForm.getUname();
//		String upass=addForm.getUpass();
//		Hb user =new Hb(uid,uname,upass);
//		HBDAO dao =new HBDAO();
//		dao.AddHB(user);
//		dao.closeSession();
//		return null;
//		 if (isCancelled(request)){
//	            System.out.println("Cancel");
//	            return mapping.findForward("go");
//	        }
//		 

		
		AddForm addForm = (AddForm) form;
		int uid=addForm.getUid();
		String name=addForm.getUname().toString();
		System.out.println("1."+name);
		String pass=addForm.getUpass().toString();
		Hb user=new Hb(uid,name,pass);
		HBDAO dao=new HBDAO();
		dao.AddHB(user);
		List<Hb> list=dao.getAll();
		dao.closeSession();
	
		request.getSession().setAttribute("rs",list);
		return mapping.findForward("go");
//		return null;
		
		
		
	}
	
	
	
}