package com.onetomany;

import java.util.HashSet;
import java.util.Set;

/**
 * Catelog generated by MyEclipse Persistence Tools
 */

public class Catelog implements java.io.Serializable {

	// Fields

	private Integer cid;

	private String cname;

	

	// Constructors

	/** default constructor */
	public Catelog() {
	}

	/** minimal constructor */
	public Catelog(String cname) {
		this.cname = cname;
	}

	// Property accessors

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	

}