package com.onetomany;

/**
 * Pp generated by MyEclipse Persistence Tools
 */

public class Pp implements java.io.Serializable {

	// Fields

	private Integer pid;

	private Catelog catelog;

	private String pname;

	// Constructors

	/** default constructor */
	public Pp() {
	}

	/** full constructor */
	public Pp(Catelog catelog, String pname) {
		this.catelog = catelog;
		this.pname = pname;
	}

	// Property accessors

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Catelog getCatelog() {
		return this.catelog;
	}

	public void setCatelog(Catelog catelog) {
		this.catelog = catelog;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

}