package com.taifook.mtss.mss.common.constant;

/**
 * This class defines the MSS function id.
 * It is generated by ACL Excel.
 * Please remember to maintain the ACL too if you add entry in it.
 *
 */
public interface MssCoreFunctionId {

    public static final String CURRENCY_MAINTENANCE = "MAS_M_CCY_MAIN";

}
