/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.usc.manager.userManager;
import com.usc.struts.form.LoginForm;
import com.usc.struts.form.RegForm;
import com.usc.util.User;


/** 
 * MyEclipse Struts
 * Creation date: 06-07-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action
{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private userManager um;

	public void setUm(userManager um)
	{
		this.um = um;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method
			
		User user = new User();
		
		user.setUsename(loginForm.getUsername().trim());
		user.setPassword(loginForm.getPassword().trim());
//		
		if(!um.checkuser(user))
		{
			return new ActionForward("/userunexisterror.jsp");
		}
		else{
			return mapping.findForward("loginsuccess");
		}
	}
}