/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-06-2009
 * 
 * XDoclet definition:
 * @struts.form name="regForm"
 */
public class RegForm extends ActionForm
{
	/*
	 * Generated fields
	 */

	/** uconfirmpass property */
	private String uconfirmpass;

	/** upass property */
	private String upass;

	/** uname property */
	private String uname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request)
	{
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request)
	{
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the uconfirmpass.
	 * @return String
	 */
	public String getUconfirmpass()
	{
		return uconfirmpass;
	}

	/** 
	 * Set the uconfirmpass.
	 * @param uconfirmpass The uconfirmpass to set
	 */
	public void setUconfirmpass(String uconfirmpass)
	{
		this.uconfirmpass = uconfirmpass;
	}

	/** 
	 * Returns the upass.
	 * @return String
	 */
	public String getUpass()
	{
		return upass;
	}

	/** 
	 * Set the upass.
	 * @param upass The upass to set
	 */
	public void setUpass(String upass)
	{
		this.upass = upass;
	}

	/** 
	 * Returns the uname.
	 * @return String
	 */
	public String getUname()
	{
		return uname;
	}

	/** 
	 * Set the uname.
	 * @param uname The uname to set
	 */
	public void setUname(String uname)
	{
		this.uname = uname;
	}
}