/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import java.lang.reflect.InvocationTargetException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sun.org.apache.commons.beanutils.BeanUtils;
import com.usc.dao.Student;
import com.usc.service.studentService;
import com.usc.struts.form.AddStudentForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-15-2009
 * 
 * XDoclet definition:
 * @struts.action path="/addStudent" name="addStudentForm" input="/addStudent.jsp" scope="request" validate="true"
 */
public class AddStudentAction extends Action
{
	private Student s;
	private studentService ss;
	public void setSs(studentService ss)
	{
		this.ss = ss;
	}

	public void setS(Student s)
	{
		this.s = s;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		
		
		AddStudentForm addStudentForm = (AddStudentForm) form;// TODO Auto-generated method stub
//		System.out.println(addStudentForm.getSname()+"------"+addStudentForm.getGname()+"------"+addStudentForm.getSex());
		try
		{
			BeanUtils.copyProperties(s,addStudentForm);
		} catch (IllegalAccessException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
//		System.out.println(s.getGname()+s.getSno());
		if(ss.findbysno(s.getSno()))
		{
			return mapping.findForward("error");
		}
		else
		ss.addStudent(s);
		
		return mapping.findForward("success");
	}
}