/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.omg.CORBA.PRIVATE_MEMBER;

import com.usc.dao.Grade;
import com.usc.service.studentService;
import com.usc.service.studentServiceImpl;

/** 
 * MyEclipse Struts
 * Creation date: 06-16-2009
 * 
 * XDoclet definition:
 * @struts.action path="/init" name="initForm" input="/form/init.jsp" scope="request" validate="true"
 */
public class InitAction extends Action
{
	private studentService ss;
	
	/*
	 * Generated Methods
	 */

	public void setSs(studentService ss)
	{
		this.ss = ss;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		
		
//		System.out.println("exectute .....");
//		InitForm initForm = (InitForm) form;// TODO Auto-generated method stub
		List gradelist = new ArrayList();
//		gradelist.add("061");
//		gradelist.add("062");
//		request.getSession().setAttribute("gradelist", gradelist);
		
//		List g = ss.getAllGrade();
//		System.out.println(ss.getAllGrade().size());
		for(Grade glist : ss.getAllGrade())
		{
			gradelist.add(glist.getGname());
//			System.out.println("+++"+glist.getGname());
		}
		request.getSession().setAttribute("gradelist", gradelist);
//		List s = ss.getAllGrade();

//		request.getSession().setAttribute("gradelist", ss.getAllGrade().get(1));
		return mapping.findForward("success");
	}
}