/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.usc.service.pageModel;
import com.usc.service.studentService;

/**
 * MyEclipse Struts Creation date: 06-17-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/listAllStudent" name="listAllStudentForm"
 *                input="/listAllStudent.jsp" scope="request" validate="true"
 */
public class ListAllStudentAction extends Action
{
	private studentService ss;
	private pageModel pm;
	public void setPm(pageModel pm)
	{
		this.pm = pm;
	}


	public void setSs(studentService ss)
	{
		this.ss = ss;
	}
	
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
//		System.out.println("listallstudent");
//		System.out.println(ss.getAllStudnet().size());
//		List studentlist = new ArrayList();
//		for(Student slist : ss.getAllStudnet())
//		{
//			studentlist.add(slist);
//			System.out.println("+++"+slist.getGname());
//		}
//		List studentlist = new ArrayList();
//		try
//		{
//			BeanUtils.copyProperties(studentlist,ss.getAllStudnet());
//		} catch (IllegalAccessException e)
//		{
//			e.printStackTrace();
//		} catch (InvocationTargetException e)
//		{
//			e.printStackTrace();
//		}
//		System.out.println(studentlist.size());
//		request.setAttribute("studentlist", ss.getAllStudnet());
//
//		return mapping.findForward("success");
		int pageNo;
		try
		{
			pageNo = Integer.parseInt(request.getParameter("pageNo"));
		} catch (NumberFormatException e)
		{
			// TODO Auto-generated catch block
			pageNo = 1;
//			e.printStackTrace();
		}
		request.setAttribute("studentlist", ss.getAllStudentbyPage(pageNo));
		request.setAttribute("pageModel", pm);
		return mapping.findForward("success");
		
	}
}