/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;



import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.usc.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-15-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action
{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
			
		HttpSession session= request.getSession();
		session.setAttribute("login", "true");
		String requrl = session.getAttribute("requrl").toString();
//		System.out.println("action..."+requrl);
//		System.out.println("execute");
//		System.out.println("1...."+session.getAttribute("login"));
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
//		List sex = new ArrayList();
//		sex.add("nan");
//		return null;
////		1.方法一
//		return new ActionForward("/index.jsp");
		
//		2.方法二
		try
		{
//			System.out.println("contextpath"+request.getContextPath());
//			System.out.println(request.getContextPath()+ requrl);
			response.sendRedirect(requrl);
		} catch (IOException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
		
//		3.方法三
//		return mapping.findForward("success");
		
		
	}
}