/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.usc.dao.Student;
import com.usc.service.studentService;
import com.usc.struts.form.SearchbynoForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/searchbyno" name="searchbynoForm" input="/searchbyno.jsp" scope="request" validate="true"
 */
public class SearchbynoAction extends Action
{
	private Student s;
	private studentService ss;
	public void setSs(studentService ss)
	{
		this.ss = ss;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SearchbynoForm searchbynoForm = (SearchbynoForm) form;// TODO Auto-generated method stub
		
//		System.out.println("searchbynoForm==="+ss.searchbyname(searchbynoForm.getsno()));
//		request.removeAttribute("student");
		request.setAttribute("student", ss.searchbyno(searchbynoForm.getsno()));
		return mapping.findForward("success");
	}
}