/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.usc.struts.form.UpdateStudentForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-17-2009
 * 
 * XDoclet definition:
 * @struts.action path="/updateStudent" name="updateStudentForm" input="/updateStudent.jsp" scope="request" validate="true"
 */
public class UpdateStudentAction extends Action
{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		UpdateStudentForm updateStudentForm = (UpdateStudentForm) form;// TODO Auto-generated method stub
		return null;
	}
}