/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import java.lang.reflect.InvocationTargetException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sun.org.apache.commons.beanutils.BeanUtils;
import com.usc.dao.Student;
import com.usc.service.studentService;
import com.usc.struts.form.UpdateStudentForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-17-2009
 * 
 * XDoclet definition:
 * @struts.action path="/updateStudent" name="updateStudentForm" input="/updateStudent.jsp" scope="request" validate="true"
 */
public class UpdateStudentAction extends Action
{
	private Student s;
	private studentService ss;
	public void setSs(studentService ss)
	{
		this.ss = ss;
	}

	public void setS(Student s)
	{
		this.s = s;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		UpdateStudentForm updateStudentForm = (UpdateStudentForm) form;// TODO Auto-generated method stub
		try
		{
			BeanUtils.copyProperties(s, updateStudentForm);
		} catch (IllegalAccessException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
//		System.out.println(request.getSession().getAttribute("beforesno"));
//		System.out.println(s.getSno());
		//!s.getSno().equals( request.getSession().getAttribute("beforesno"))&& 
		ss.deleteStudent(request.getSession().getAttribute("beforesno").toString());
		if(ss.findbysno(s.getSno()))
		{
			return mapping.findForward("error");
		}
		ss.updateStudent(s);
		
		return mapping.findForward("success");
	}
}