package com.pojo;

/**
 * Hb generated by MyEclipse Persistence Tools
 */

public class Hb implements java.io.Serializable {

	// Fields

	private Integer uid;

	private String uname;

	private String upass;

	// Constructors

	/** default constructor */
	public Hb() {
	}

	/** full constructor */
	public Hb(Integer uid, String uname, String upass) {
		this.uid = uid;
		this.uname = uname;
		this.upass = upass;
	}

	// Property accessors

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpass() {
		return this.upass;
	}

	public void setUpass(String upass) {
		this.upass = upass;
	}

}