/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.usc.service.studentService;


/** 
 * MyEclipse Struts
 * Creation date: 06-17-2009
 * 
 * XDoclet definition:
 * @struts.action path="/deleteStudent" name="deleteStudentForm" input="/deleteStudent.jsp" scope="request" validate="true"
 */
public class DeleteStudentAction extends Action
{
	private studentService ss;

	public void setSs(studentService ss)
	{
		this.ss = ss;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		String sno = request.getParameter("sno");
//		System.out.println(sno);
		ss.deleteStudent(sno);
		return mapping.findForward("success");
	}
}