/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.usc.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.usc.dao.Student;
import com.usc.service.studentService;
import com.usc.struts.form.SerachbynameForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/serachbyname" name="serachbynameForm" input="/serachbyname.jsp" scope="request" validate="true"
 */
public class SerachbynameAction extends Action
{
	private Student s;
	private studentService ss;
	public void setSs(studentService ss)
	{
		this.ss = ss;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SerachbynameForm serachbynameForm = (SerachbynameForm) form;// TODO Auto-generated method stub
//		request.removeAttribute("student");
		request.setAttribute("student", ss.searchbyname(serachbynameForm.getsname()));
		return mapping.findForward("success");
	}
}