/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-12-2008
 * 
 * XDoclet definition:
 * @struts.form name="indexForm"
 */
public class IndexForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** uname property */
	private String uname;

	/** upass property */
	private String upass;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the uname.
	 * @return String
	 */
	public String getUname() {
		return uname;
	}

	/** 
	 * Set the uname.
	 * @param uname The uname to set
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/** 
	 * Returns the upass.
	 * @return String
	 */
	public String getUpass() {
		return upass;
	}

	/** 
	 * Set the upass.
	 * @param upass The upass to set
	 */
	public void setUpass(String upass) {
		this.upass = upass;
	}
}