/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class LoginForm extends ActionForm {
	
	private Map map=new  HashMap();
	public Object  getMapByKey(String key) {
		return map.get(key);
	}


	public void setMap(String key,Object obj) {
		System.out.println(key+"   "+obj.toString());
		this.map.put(key, obj);
	}


	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		
		return null;
	}

	
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.map.clear();
	}


	public Map getMap() {
		return map;
	}


	public void setMap(Map map) {
		this.map = map;
	}
}